apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: devpulse-notification-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/devpulse_notifications"
            - name: SPRING_DATASOURCE_USERNAME
              value: "devpulse"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "devpulse"
            - name: SPRING_DATA_REDIS_HOST
              value: "host.docker.internal"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "host.docker.internal:9092"