debug: enable

server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration

  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      server:
        webmvc:
          forwarded-request-headers-filter:
            enabled: false
          enabled: true
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: feed-service
              uri: ${FEED_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/feed/**
              filters:
                - StripPrefix=1
            - id: media-service
              uri: ${MEDIA_SERVICE_URI:http://localhost:8084}
              predicates:
                - Path=/media/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: ${spring.application.name}.log

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
