spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  graphql:
    path: /graphql
    websocket:
      path: /graphql-ws
      connection-idle-timeout: 60s
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: ${spring.application.name}.log