server:
  port: 8083

spring:
  application:
    name: notification-service

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/devpulse_notifications}
    username: ${SPRING_DATASOURCE_USERNAME:devpulse}
    password: ${SPRING_DATASOURCE_PASSWORD:devpulse}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  graphql:
    graphiql:
      enabled: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-service-group
#      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  distribution:
    percentiles-histogram:
      http:
        server:
          requests: true
  tracing:
    enabled: true
    propagation:
      type: B3
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,prometheus,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: ${spring.application.name}.log
  level:
    com.devpulse: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG